M48
; DRILL file {KiCad 8.0.1} date 2024-04-20T10:16:07+1200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-20T10:16:07+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X136.0Y-90.5
T2
X129.5Y-86.3
X142.0Y-86.3
X142.0Y-100.5
M30
