title: Collective Project
description: A Helicopter Collective controller for flight sim use
theme: just-the-docs

url: https://sparkz-nz.github.io/collective

aux_links:
  Sparkkz Maker Notes: https://sparkz-nz.github.io/
